In [ ]:
from google.colab import drive
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).


In [ ]:
import spacy as sp
# Industrial-Strength Natural Language Processing
is_using_gpu = sp.prefer_gpu()
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
dataset=pd.read_csv("/content/goodreads_books_small.csv")
dataset


id  ... Unnamed: 47
0       630104  ...         NaN
1         9487  ...         NaN
2      6050894  ...         NaN
3        39030  ...         NaN
4          998  ...         NaN
...        ...  ...         ...
9995     24867  ...         NaN
9996  38393457  ...         NaN
9997  28692897  ...         NaN
9998  41165488  ...         NaN
9999  44415628  ...         NaN

[10000 rows x 48 columns]

In [ ]:
data1=dataset[['title','description']]
data1

title                                        description
0                                          Inner Circle  Reed Brennan arrived at Easton Academy expecti...
1                                     A Time to Embrace  Ideje az ölelésnek Történet a reményről,...
2                                              Take Two  Filmmakers Chase Ryan and Keith Ellison have c...
3                                             Reliquary                                                NaN
4     The Millionaire Next Door: The Surprising Secr...  The incredible national bestseller that is cha...
...                                                 ...                                                ...
9995  Anne McCaffrey Freedom Collection: Freedom's L...  Freedom's Landing - read by Susie Breck, direc...
9996                  Break the Bodies, Haunt the Bones  Jane is haunted. Since she w Jane is haunted. ...
9997                                   Самодива  Теодора Славин пристига Ð...
9998                 Brief Answers to the Big Questions  Stephen Hawking was the most renowned scientis...
9999                                 Elf and Efficiency  A tale of greed and corruption. Santa is in tr...

[10000 rows x 2 columns]

In [ ]:
print(data1['title'][0])

Inner Circle


In [ ]:
data1['description'] =data1['description'].astype(str)
# we take the description 
data1['len']=data1['description'].apply(lambda x:len(x.split(' ')))
bookdf=data1[data1['len']>=50]
# bookdf.shape

import en_core_web_sm
nlp = en_core_web_sm.load()
import re
def clean_text(doc):
    #Clean the document. Remove pronouns, stopwords, lemmatize the words and lowercase them
    doc = nlp(doc)
    tokens = []
    exclusion_list = ["nan"]
    for token in doc:
        if token.is_stop or token.is_punct or token.text.isnumeric() or (token.text.isalnum()==False) or token.text in exclusion_list :
            continue
        token = str(token.lemma_.lower().strip())
        tokens.append(token)
    return " ".join(tokens) 
bookdf['cleaned_description']=bookdf.apply(lambda row: clean_text(row["description"]) ,axis=1)
bookdf.reset_index(inplace=True)

# newdf=bookdf[['title','description','cleaned_description']]
newdf=bookdf[['title','cleaned_description']]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try usi

In [ ]:
newdf.to_csv('data.csv')
!cp data.csv "drive/My Drive/"

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
newdf['title_id']=le.fit_transform(newdf['title'])
contentdf=newdf[['title_id','title','description','cleaned_description']]
contentdf=contentdf.set_index('title_id')
contentdf.reset_index(inplace=True)
#contentdf.drop(['index'],axis=1,inplace=True)
# contentdf

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
tfidf = TfidfVectorizer(sublinear_tf=True, min_df=3,ngram_range=(1, 3), stop_words='english')
tfidf_description = tfidf.fit_transform((contentdf["cleaned_description"])) 
print("Each of the %d text is represented by %d features (TF-IDF score of unigrams and bigrams)" %(tfidf_description.shape)) 
# Finding cosine similarity between vectors 
from sklearn.metrics.pairwise import cosine_similarity 
cos_sim = linear_kernel(tfidf_description, tfidf_description) 


indices = pd.Series(contentdf.index) 
def recommendations(title, cosine_sim = cos_sim): 
    recommended_book = [] 
    index = indices[indices == title].index[0]
    similarity_scores = pd.Series(cosine_sim[index]).sort_values(ascending = False) 
    top_10_books = list(similarity_scores.iloc[1:11].index)
    for i in top_10_books: 
        recommended_book.append(list(contentdf.index)[i]) 
    top_5_books=[]
    for i in recommended_book:
        if i not in top_5_books and i!=title:
            top_5_books.append(i)
    recommendbook=[]
    for i in top_5_books:
        recommendbook.append(contentdf['title'][i])
    return recommendbook


book="Inner Circle"
print("Enter a book you liked: ",book)
a=contentdf.loc[contentdf['title']==book]
id=a.index[0]
r=recommendations(id)
print("*****Here are a few recommendations for you*****")
for i,j in zip(r,range(1,len(r)+1)):
    print(j,".",i)



In [ ]:
newdf

title                                cleaned_description
0                                          Inner Circle  reed brennan arrive easton academy expect find...
1                                     A Time to Embrace  ideje az snek net remã ã s az ã let karen king...
2                                              Take Two  filmmaker chase ryan keith ellison complete fe...
3                                           Black Sheep  high spirited intelligence good look abigail w...
4                                             Sylvester  news go sylvester rayne elegant impeccable duk...
...                                                 ...                                                ...
8630  Anne McCaffrey Freedom Collection: Freedom's L...  freedom landing read susie breck direct ruth b...
8631                  Break the Bodies, Haunt the Bones  jane haunt w jane haunt child carry ghost girl...
8632                                   Самодива  ð² ð½ð ð¼ð ð² ð½ð ð² ð ð ð½ð ð½ðµ ð ðµ ð² ð½ð ...
8633                 Brief Answers to the Big Questions  stephen hawking renowned scientist einstein kn...
8634                                 Elf and Efficiency  tale greed corruption santa trouble step moder...

[8635 rows x 2 columns]

In [ ]:
print(tfidf_description)

  (0, 32006)	0.07404754449820569
  (0, 806)	0.1000501407472895
  (0, 24392)	0.1026908865910505
  (0, 8343)	0.1026908865910505
  (0, 5145)	0.1026908865910505
  (0, 23480)	0.08704884262274759
  (0, 29199)	0.1026908865910505
  (0, 29720)	0.14264993385514707
  (0, 23574)	0.1371509886117118
  (0, 3162)	0.1693996137208989
  (0, 19119)	0.17387078510083825
  (0, 8874)	0.17387078510083825
  (0, 16845)	0.1693996137208989
  (0, 19344)	0.1576220163037112
  (0, 23518)	0.10522555111173973
  (0, 6875)	0.1397124111073649
  (0, 26810)	0.14264993385514707
  (0, 9630)	0.1657464007022747
  (0, 28130)	0.1693996137208989
  (0, 31991)	0.04840089362348275
  (0, 21642)	0.0500805007130305
  (0, 802)	0.05347345166009284
  (0, 37207)	0.0558880561334148
  (0, 24307)	0.0329266574038184
  (0, 36801)	0.06263902549554064
  :	:
  (8634, 26163)	0.22701208504241574
  (8634, 9759)	0.16506539503769518
  (8634, 6390)	0.21709687536055267
  (8634, 2771)	0.2026404975221934
  (8634, 28215)	0.2701750249866549
  (8634, 29458)	0.2

In [ ]:
print(cos_sim)

[[1.         0.         0.00325611 ... 0.         0.01346822 0.01267352]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.00325611 0.         1.         ... 0.         0.01363674 0.00507293]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.01346822 0.         0.01363674 ... 0.         1.         0.00190927]
 [0.01267352 0.         0.00507293 ... 0.         0.00190927 1.        ]]


In [ ]:
contentdf.to_csv('content.csv', index = False)

In [ ]:
import pickle
string = pickle.dumps(cos_sim)
with open("a_file.txt", "wb") as f:
    f.write(string)